### ISSUE TITLE
Schlechte Performance auf einigen Geräten

### ISSUE THREAD

**Issue by DJPoles** [informatiCup/informatiCup2020#10]
Ich habe das Beispiel Python-Programm auf einem Laptop und einem PC installiert und beim Ausführen am PC ein komisches Problem mit den Antwortzeiten.
Wenn ich das Python-Programm am Laptop starte und dann die ic20-Datei ausführe, läuft das Programm super schnell durch. Wenn ich es allerdings auf dem PC starte, der deutlich leistungsstärker ist, gibt es zwischen jeder Runde einen Delay von ca. 0,5 Sekunden. Wenn ich die ic20-Datei 20 Mal gleichzeitig starte, ist der Delay immer noch bei 0,5 Sekunden, also kann es eigentlich nicht an der Leistung des PCs liegen. Hat noch jemand das Problem oder kann es ein Problem mit Windows-Sicherheits Einstellungen sein?
PS: Auf dem PC eines Freundes läuft es auch super schnell durch, es liegt also nicht an PC vs Notebook.

**Comment by DJPoles** [comment]
Ich habe das Beispiel-Programm mal so geändert, dass es am Anfang und am Ende die aktuelle Zeit ausgibt. Das Python-Programm läuft schnell durch, allerdings dauert es bis die ic20-Datei ein neues JSON schickt. Vielleicht verdeutlicht das mein Problem etwas

2019-10-29 15:33:21.810620
round: 1, outcome: pending
2019-10-29 15:33:21.812622
2019-10-29 15:33:22.158066
round: 2, outcome: pending
2019-10-29 15:33:22.161069
2019-10-29 15:33:22.515248
round: 3, outcome: pending
2019-10-29 15:33:22.517249
2019-10-29 15:33:22.862089
round: 4, outcome: pending
2019-10-29 15:33:22.865091
2019-10-29 15:33:23.211116
round: 5, outcome: pending
2019-10-29 15:33:23.215119
2019-10-29 15:33:23.559181
round: 6, outcome: pending
2019-10-29 15:33:23.562184
2019-10-29 15:33:23.906699
round: 7, outcome: pending
2019-10-29 15:33:23.909701
2019-10-29 15:33:24.253744
round: 8, outcome: pending
2019-10-29 15:33:24.256748

**Comment by BitFlipp** [comment]
Das Tool gibt nach Verarbeitung einer Aktion den resultierenden Zustand aus, bevor dieser eingegeben wird. Bei Aufruf des Tools ohne `-o` bzw. `--log-file-path` wird die Standardausgabe verwendet. Es ist denkbar, dass deren Verarbeitung konfigurationsbedingt verzögert wird.

Bitte zur Überprüfung das Tool mit dem genannten Parameter aufrufen, um eine Dateiausgabe zu erzwingen: `./ic20_windows.exe -o test.log`

**Comment by marvinsxtr** [comment]
Unser Team hat gerade dasselbe Problem. Die Ausgabe über eine Logdatei löst das Problemfür uns leider auch nicht.

**Comment by BitFlipp** [comment]
Ich konnte das Verhalten unter Windows 10 reproduzieren. Ich vermute, dass Bottle's HTTP-Entwicklungs-Server nicht optimal unter Windows 10 läuft. Bitte testweise mit einem anderen Framework versuchen. Im Anhang ein Beispiel, das Express nutzt, getestet unter Windows 10 mit NodeJS 11.6.0 und npm 6.5.0-next.0.

[icup2020_express.zip](https://github.com/informatiCup/informatiCup2020/files/3814611/icup2020_express.zip)
```
npm install
npm start
```
