### ISSUE TITLE
Zurücksetzen des Error-Status

### ISSUE THREAD

**Issue by j-moeller** [informatiCup/informatiCup2020#11]
Wenn in einer Runde mehrere Aktionen durchgeführt werden und eine davon einen Fehler auslöst, dann bleibt der Fehlerzustand in den folgenden Zuständen gesetzt (selbst wenn eine Aktion erfolgreich war).

Zum Beispiel:
- Request (initial)
- Response "deployVaccine"
- Request (error=vaccine is not available)
- Response "closeConnection"
- Request (error=vaccine is not available)

Im letzten Request hätte ich erwartet, dass error leer wäre. Wäre es möglich das Programm entsprechend anzupassen?

**Comment by BitFlipp** [comment]
Ist behoben in 2.0.1. Danke für den Hinweis!
