### ISSUE TITLE
Konnte keine Verbindung herstellen, da Zielcomputer die Verbindung verweigerte.

### ISSUE THREAD

**Issue by Sydebrix** [informatiCup/informatiCup2020#12]
Moin zusammen,

ich/wir haben die Exe jetzt mittlerweile auf vier Windows 10 x64 Rechnern ausprobiert, bekommen jedoch immer die gleiche Fehlermeldung. Admin/Kein Admin/CMD/PowerShell liefern alle das gleiche.

Grüße

<img width="576" alt="2019-11-12_20h56_48" src="https://user-images.githubusercontent.com/20229118/68705915-38d27400-058f-11ea-9a91-ea6f50cc3ac9.png">

**Comment by BitFlipp** [comment]
Bitte testet euren Webservice mit einem anderen Tool, bspw. mit PowerShell:
```
Invoke-WebRequest -Uri http://localhost:50123 -Method POST -ContentType "application/json" -Body '{"round":1,"outcome":"pending"}'
```

**Comment by Sydebrix** [comment]
Hatten wir schon, auch mit verschiedenen Versionen der PowerShell(x64/x86/ISE).
<img width="614" alt="2019-11-12_21h44_27" src="https://user-images.githubusercontent.com/20229118/68709362-d8930080-0595-11ea-85c3-f9039f847a00.png">

**Comment by Sydebrix** [comment]
Wenn man die experimentellen Features bei Docker>Daemon einschaltet, dann bekommt man angehängten Fehler. 
![docker_eof](https://user-images.githubusercontent.com/20229118/68845783-3b86b380-06cc-11ea-9fd1-526deac081ce.png)

**Comment by BitFlipp** [comment]
Lässt sich dieses Verhalten auch bei _ohne_ Docker gestarteter, unveränderter Beispiellösung beobachten?

Ich schlage vor, ein neues Issue für die Docker-Problematik zu öffnen, da ich vermute, dass sie nicht mit der ursprünglichen Problematik zusammenhängt.
