### ISSUE TITLE
Maximale Anzahl der Städte

### ISSUE THREAD

**Issue by pgronau** [informatiCup/informatiCup2020#14]
Moin,
wir diskutieren grade den Umfang unseres Programmes und haben uns die Frage gestellt wie viele Städte _maximal_ zu erwarten sind.

Viele Grüße

**Comment by BitFlipp** [comment]
Alle nicht in der Aufgabenstellung beschriebenen Eigenschaften des Modells müssen durch Beobachtungen abgeleitet werden. Bitte dokumentiert alle Annahmen, auf denen eure Lösung basiert.

Die Wertungsspiele (nach Abgabe) werden mit der letzten Version des öffentlich verfügbaren Kommandozeilenwerkzeugs durchgeführt. Es gibt keine "versteckten" Möglichkeiten der Einflussnahme auf das Modells - nur `--random-seed`.

**Comment by pgronau** [comment]
> Die Wertungsspiele (nach Abgabe) werden mit der letzten Version des öffentlich verfügbaren Kommandozeilenwerkzeugs durchgeführt. Es gibt keine "versteckten" Möglichkeiten der Einflussnahme auf das Modell - nur --random-seed.

Ah, das muss ich in der pdf überlesen haben.

Vielen Dank!
