### ISSUE TITLE
Fehlerausgabe bei Input in die Exe

### ISSUE THREAD

**Issue by Mathu1998** [informatiCup/informatiCup2020#15]
Wenn wir mit der Exe (Kommandozeilenwerkzeug) unsere, in AWS erzeugte, Schnittstelle anfragen, lässt sich in der Logdatei festellen, dass bei der ersten Antwort eine "normale" erste Runde an die Schnittstelle übergeben wird. Die Exe registriert/akzeptiert unsere Antwort ("{\"type\": \"endRound\"}") jedoch nicht und gibt uns erneut eine "erste Runde Antwort", diesmal jedoch mit einem error (failed to decode action). 
Liegt das daran, dass unsere Schnittstelle den falschen Datentypen zurückgibt bzw. welchen Datentyp erwartet die Exe? 

Erste Antwort:
![Erster Request](https://user-images.githubusercontent.com/57688487/69430273-7e343580-0d35-11ea-9397-2bcbc4b25a6e.png)

Zweite Antwort mit Fehler:
![Zweiter Request mit Fehler](https://user-images.githubusercontent.com/57688487/69430375-c2bfd100-0d35-11ea-8cf5-bd3fd6da3dc2.png)

**Comment by BitFlipp** [comment]
Ich vermute, dass ihr ein API Gateway verwendet und dieses falsch konfiguriert ist. Bitte stellt die Ausgabe einer Anfrage mit [HTTPie](https://httpie.org) (oder einem vergleichbaren Tool) hier zur Verfügung. Im unteren Beispiel ist die Adresse des Webservice der Beispiellösung (`localhost:50123`) durch die Adresse eures Webservice zu ersetzen.

```
http localhost:50123 round=1 outcome='pending'
```

HTTPie-Ausgabe:
```
HTTP/1.0 200 OK
Content-Length: 20
Content-Type: application/json
Date: Fri, 22 Nov 2019 15:48:31 GMT
Server: WSGIServer/0.2 CPython/3.8.0

{
    "type": "endRound"
}
```

Siehe auch https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-getting-started-with-rest-apis.html.

**Comment by Mathu1998** [comment]
Unsere Ausgabe sieht wie folgt aus. Möglicherweise ist es noch wichtig anzumerken, dass wir die Antwort in AWS durch einen, in Java geschriebenen, requestHandler erzeugen. Wir haben aus Testgründen zwei Schnittstellen bereitgestellt, die jeweils mit einem String bzw. JSON-Objekt antworten. 

Ausgabe als String:

![Ausgabe String](https://user-images.githubusercontent.com/57688487/69494348-ea8c7180-0eba-11ea-97fc-316f0201ad6b.png)

Ausgabe als JSON:

![Ausgabe JSON](https://user-images.githubusercontent.com/57688487/69494353-f5470680-0eba-11ea-86ca-8feca389e2a8.png)

**Comment by BitFlipp** [comment]
Tatsächlich ist `"{\"type\": \"endRound\"}"` gültiges JSON, bildet aber den _String_ `{"type": "endRound"}` ab. Das Kommandozeilenwerkzeug erwartet ein _Objekt_ in JSON. Vielleicht hilft https://docs.aws.amazon.com/lambda/latest/dg/java-handler-io-type-pojo.html.

**Comment by BitFlipp** [comment]
Ich wollte mit meinem etwas kryptischen Beitrag sagen, dass euer zweiter Webservice _auch_ einen String in JSON zurückgibt :o)

**Comment by Mathu1998** [comment]
Vielen Dank für die Hilfe, mittlerweile haben wir es geschafft :)
