### ISSUE TITLE
Mobilität

### ISSUE THREAD

**Issue by Milln** [informatiCup/informatiCup2020#16]
Mobilität von Pathogenen wird in der Angabe mit "Wie wahrscheinlich ist der Übergang des Keims auf nicht verbundene Städte?" beschrieben. Hierzu zwei Fragen:

1. Können Sie nähere Angaben zu "nicht verbundenen Städten" geben? Heißt das, dass jede beliebige Stadt jede andere anstecken kann, oder müssen diese Städte geographisch nah beieinander liegen?
2. Wie ist dann die Infektionsrate über Flugverbindungen definiert? Ist sie gleich der Mobilität? Oder haben wir diesbezüglich keine Angaben?

Vielen Dank!

**Comment by BitFlipp** [comment]
Beide Fragen lassen sich durch Beobachtungen beantworten.
