### ISSUE TITLE
Events in den Städten

### ISSUE THREAD

**Issue by MarkusGersdorf** [informatiCup/informatiCup2020#17]
Moin zusammen,

wir haben festgestellt, dass die Städte nicht immer ein Event zurückgeben.
Wenn z.B. ein Flughafen geschlossen wird, bekommt man folgende Antwort:
`"events": [{"type": "airportClosed", "sinceRound": 1, "untilRound": 2}]`.
Wenn aber z.B. politischer Einfluss geltend gemacht wird, dann bekommt man im Antwort JSON kein Event mit der letzen Aktion die ausgeführt wurde. Ist das richtig so, dass bei den Aktionen nicht mit einem Event geantwortet wird?

**Comment by BitFlipp** [comment]
> Ist das richtig so, dass bei den Aktionen nicht mit einem Event geantwortet wird?

Es ist so implementiert. Ich sehe aber ein, dass es inkonsequent ist, dass es ein "medicationDeployed"-Ereignis, aber kein "influenceExerted"-Ereignis gibt. Kommt zeitnah in Version 2.0.3.

**Comment by MarkusGersdorf** [comment]
Danke.
