### ISSUE TITLE
Bioterrorismus

### ISSUE THREAD

**Issue by rouvenR** [informatiCup/informatiCup2020#19]
Lässt sich Bioterrorismus durch bestimmte Aktionen bekämpfen?

Wir sind uns recht sicher, dass wir dies schon einmal durch Medikamente verteilen erreicht haben, obwohl das Bioterrorismus kein "prevalence" Attribut besitzt.

In einem anderen Seed (53) hatten wir nun aber den Fall, dass der Bioterrorismus ein Pathogen besaß, das bereits im Spiel vorkam und ausgelöscht war. Hier haben wir auf die Stadt alle Aktionen zig fach angewandt (Quarantäne, Medikamente (mehr als 20 mal), Impfung, alle Städtewerte auf ++). Ist das ein Bug, sind wir auf dem falschen Weg oder lässt sich Bioterrorismus schlichtweg nicht bekämpfen?

**Comment by BitFlipp** [comment]
`bioTerrorism` ist permanent. Permanente Events ermöglichen Rückschlüsse auf vergangene Spielzustände. Im Gegensatz zu temporären Events verschwinden permanente Events nie. Ein weiteres Beispiel: `vaccineInDevelopment` ist temporär und wird im Laufe des Spiels ersetzt durch das permanente `vaccineAvailable`.

Wenn ihr es geschafft habt, dass `bioTerrorism` verschwindet, bitte ich um Schritte zur Reproduktion.

**Comment by rouvenR** [comment]
Alles klar, danke.
Wahrscheinlich hatten wir es dann einfach falsch in Erinnerung ...
