### ISSUE TITLE
Parametereingabe bei Windows .exe

### ISSUE THREAD

**Issue by malte-b** [informatiCup/informatiCup2020#2]
Wie kann ich bei der Windows .exe den Parameter --help eingeben? Wenn ich das Programm starte, kann ich nichts eingeben und das Fenster schließt sich auch von selbst wieder.

**Comment by AlexPaar** [comment]
Einfach einen Command Prompt öffnen und das Kommandozeilenwerkzeug von der Konsole starten.

![Capture](https://user-images.githubusercontent.com/600435/66085194-de49ff00-e570-11e9-91fe-9967047900e1.PNG)
