### ISSUE TITLE
Amazon Gateway API Logs

### ISSUE THREAD

**Issue by markusradtke** [informatiCup/informatiCup2020#20]
Unser Team möchte für das Deployment Amazon AWS Lambda verwenden, mit einer vorgeschalteten Gateway API. Anscheinend gibt es Probleme beim Rückversand der Antwortdaten unseres Programms an das Kommandozeilentool, denn mit Testdaten auf Amazon selbst läuft alles einwandfrei. ("Error: Errors: action type is missing")

Leider finde ich keine Möglichkeit Logs der API anzusehen, wie die ausgehenden Antworten aussehen.
Gibt es dort eine Möglichkeit?

**Comment by BitFlipp** [comment]
Hilft #15?

**Comment by markusradtke** [comment]
Oh ja, sehr sogar. Es funktioniert jetzt. 
Vielen Dank!
