### ISSUE TITLE
Schlechtere Ergibnisse mit neuer game.exe

### ISSUE THREAD

**Issue by rouvenR** [informatiCup/informatiCup2020#21]
Unsere Lösung hat sich in letzter Zeit verschlechtert, weswegen wir Stunden damit verbracht haben, unseren Code nach dem Grund dafür zu durchsuchen. Nun ist uns aufgefallen, dass es nicht mit dem Code zusammenhängt, sondern mit der neuen game.exe. Mit der, die wir am Anfang bereitgestellt bekommen haben, haben wir eine um 15-25% bessere Lösung als mit der neuen. Wir sind uns nicht sicher, ob das Spiel absichtlich "schwerer" gemacht wurde oder dies unbeabsichtigt durch scheinbar neutrale Bugfixes passiert ist.

Bitte um Aufklärung.

**Comment by BitFlipp** [comment]
Welche Versionen des Kommandozeilenwerkzeugs habt ihr für den Vergleich verwendet?

**Comment by rouvenR** [comment]
Die allererste, also v1.0.0 vom 25. September (bessere Ergebnisse) und die neueste, also v2.1.0 vom 5. Dezember (schlechtere Ergebnisse).

**Comment by BitFlipp** [comment]
Vermutlich 2.0.1 auf 2.0.2 vom 20.11.2019 (#13).

**Comment by rouvenR** [comment]
Hm, irgendwie können wir uns nicht erklären, warum diese Änderung einen so gravierenden Unterschied machen sollte ... Können wir im Handbuch spezifizieren, welche Version für den Test verwendet werden soll?

**Comment by BitFlipp** [comment]
Quarantäne war - entgegen der Spezifikation - permanent, s. #13. Das wirkt sich enorm auf das Spielgeschehen aus.

> Können wir im Handbuch spezifizieren, welche Version für den Test verwendet werden soll?

Die Wertungsspiele werden mit der aktuellen Version (2.1.0, 05.12.2019) durchgeführt. Die Ergebnisse der Wertungsspiele sind nur ein Bewertungskriterium von vielen (-> wissenschaftliche Ausarbeitung).
