### ISSUE TITLE
Timeout bis zur Rückgabe der Antwort

### ISSUE THREAD

**Issue by michip** [informatiCup/informatiCup2020#22]
Gibt es eine Zeitbeschränkung wie lange unser Server für die Antwort auf einen Game State brauchen darf? Falls nein, dürfen wir dann in unserer Erklärung zur Ausführung vermerken, dass das Spiel immer mit dem Parameter -t 0 ausgeführt werden muss?

**Comment by BitFlipp** [comment]
Eine harte Zeitbeschränkung erlegt die Aufgabenstellung nicht auf, weil Auslastung des ausführenden Rechners und Netzwerklatenzen die Antwortzeiten eures Dienstes beeinflussen.

Bitte bedenkt aber, dass bei einer durchschnittlichen Antwortzeit von einer Minute bereits ein einziges Wertungsspiel mit 120 Runden 2 Stunden dauert.

**Comment by BitFlipp** [comment]
Vermutlich 2.0.1 auf 2.0.2 vom 20.11.2019 (#13).
