### ISSUE TITLE
Nur ein Ausbruch pro Stadt

### ISSUE THREAD

**Issue by ChristophScn** [informatiCup/informatiCup2020#25]
Nach unseren Tests ist ab Version 1.1.0 nur noch ein Ausbruch pro Stadt möglich. Die vorherigen Versionen (1.0.0 und 1.0.1) erlauben auch mehrere Ausbrüche pro Stadt. Ist dies gewollt?

**Comment by jasZnerol** [comment]
Ja.

**Comment by AlexPaar** [comment]
Ja.
