### ISSUE TITLE
wo finde ich den Sourcecode vom CLI?

### ISSUE THREAD

**Issue by gumulka** [informatiCup/informatiCup2020#3]
Bei Source Code gibt es nur einen snapshot des repositories, was jetzt aber nicht das Tool ist.

**Comment by BitFlipp** [comment]
Wir halten den Quelltext unter Verschluss, um die Modellanalyse nicht zu trivialisieren. 

Sicherlich wirft dies Sicherheitsbedenken auf. Datei- und Netzwerkzugriffe des Tools lassen sich unter Linux mit strace protokollieren (`strace -v -e trace=file,network -f ./ic20_linux > /dev/null`), unter macOS mit DTrace, unter Windows mit WinDbg. Sandboxing und Virtualisierung sind auch Optionen.

**Comment by jonico** [comment]
@BitFlipp: kann der Quellcode nach Ende der Endrunde freigegeben werden?

**Comment by jonico** [comment]
here you: https://github.com/informatiCup/informatiCup2020/tree/master/src
🎉
