### ISSUE TITLE
Dateinamen bei Dateilogging

### ISSUE THREAD

**Issue by gumulka** [informatiCup/informatiCup2020#4]
Kann es bitte möglich gemacht werden, den Dateinamen anzugeben beim Loggen um eine definierte Datei zu haben und den log nicht unbedingt den Seed zu nehmen. Vielleicht ein Parameter -f mit defaultwert Seed?

**Comment by BitFlipp** [comment]
Wird ermöglicht mit dem nächsten Release im Laufe der nächsten Tage.

Bis dahin bitte stdout umleiten:
> ./ic20_windows.exe -s 123456 > beliebiger_name.log
