### ISSUE TITLE
Unveränderliche Eigenschaften

### ISSUE THREAD

**Issue by j-moeller** [InformatiCup/InformatiCup2020#5]
In der Aufgabenstellung ist beschrieben, dass Pathogene und Städte unveränderliche Eigenschaften haben. Heißt das, dass wir (generell und speziell für die Evaluation) annehmen können, dass:
 - Die Städte + Stadtverbindungen identisch sein werden (also keine neuen Städte/Verbindungen eingeführt werden oder bestehende geändert werden)
- Nur Pathogene verwendet werden, die auch im ic20_* Programm enthalten sind (d.h. eine bestimmte Menge an Pathogenen erwartet werden kann)

**Comment by BitFlipp** [comment]
Die Aufgabenstellung wurde aktualisiert im Bestreben, das Konzept der "Unveränderlichkeit" weniger missverständlich darzustellen. Bitte um Rückmeldung, ob damit die Fragen beantwortet sind oder noch weiterer Klärungsbedarf besteht.

**Comment by j-moeller** [comment]
Danke für die Rückmeldung. Die Änderungen verstehe ich so, dass beide Antworten mit "Ja" beantwortet werden können. Wenn das zutrifft, kann der Issue geschlossen werden.
