### ISSUE TITLE
Klarstellung wo sich die CLI tools befinden

### ISSUE THREAD

**Issue by robinhundt** [informatiCup/informatiCup2020#6]
In der Projektbeschreibung ist lediglich ein Link auf dieses Repo zu finden. Ein kleiner Hinweis darauf, dass die Binaries unter `Releases` zur Verfügung gestellt sind und nicht im Repo sind (was ja auch durchaus richtig so ist :sweat_smile:), würde Nutzern die mit Github nicht so vertraut sindm Sucharbeit ersparen.

**Comment by AlexPaar** [comment]
In der Aufgabenstellung gibt es jetzt einen direkten [Link](https://github.com/InformatiCup/InformatiCup2020/releases/latest) zu dem aktuellen Release des Kommandozeilenwerkzeugs.
