### ISSUE TITLE
Lernen der Ereignistypen

### ISSUE THREAD

**Issue by pgronau** [informatiCup/informatiCup2020#7]
Moin,
wir haben uns in der Gruppe die Frage gestellt, ob wir:

1. die Ereignistypen manuell auswerten sollen

oder

2. die Software alle Ereignistypen lernen und ihr Handeln an diese Typen anpassen soll

Ich beziehe mich auf folgenden Absatz:

> Die verschiedenen Ereignistypen, die während eines Spiels auftreten können, sind Ihnen zunächst nicht bekannt und müssen gelernt werden. Dies umfasst die unterschiedlichen Eigenschaften der Ereignistypen und deren Auswirkungen auf das Spielgeschehen. Manche Ereignisse lassen Rückschlüsse auf vorige Spielzustände zu. Die Menge der Ereignis-Typen ist begrenzt. Nach hinreichend vielen Spielen werden Sie alle Ereignistypen gesehen haben.

Viele Grüße

**Comment by AlexPaar** [comment]
Wir haben die Aufgabenstellung an dieser Stelle angepasst. Meldet Euch bitte nochmal wenn noch nicht alles klar ist.
