### ISSUE TITLE
Verwendung des Kommandozeilenwerkzeuges unter MacOS

### ISSUE THREAD

**Issue by DJPoles** [informatiCup/informatiCup2020#8]
Hallo,

wie genau verwende ich das Kommandozeilenwerkzeug unter MacOS? Unter Windows kann ich es mit "ic20_windows.exe" in der Konsole aufrufen, aber das funktionert auf MacOS (mit dem entsprechenden Kommandozeilenwerkzeug) nicht.

**Comment by BitFlipp** [comment]
Bitte die Datei zunächst ausführbar machen:
`chmod +x ic20_darwin`

Dann lässt sich das Tool so starten:
`./ic20_darwin`
